services:
  app:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      DATABASE_URL: jdbc:postgresql://db:5432/productsdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fiap-network
  db:
    container_name: postgresdb
    image: postgres:12.19-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productsdb
    networks:
      - fiap-network
    healthcheck:
      # Test is the command to run to check the health of the container
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      # The interval is the time between checks
      interval: 10s
      # The timeout is the time to wait before considering the check failed
      timeout: 5s
      # The retries is the number of attempts before considering the container unhealthy
      retries: 5

networks:
  fiap-network:
    driver: bridge