insert into categories (id, name, description, active, created_at, updated_at) values
(RANDOM_UUID(), 'Electronics', 'Devices and gadgets', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Books', 'Printed and digital books', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Clothing', 'Apparel and accessories', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Home & Kitchen', 'Furniture and appliances', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Sports & Outdoors', 'Equipment and gear', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Toys & Games', 'Fun and educational toys', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Health & Beauty', 'Personal care products', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Automotive', 'Car parts and accessories', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Music', 'CDs, vinyl, and digital music', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Movies & TV', 'DVDs and streaming services', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Pet Supplies', 'Food and accessories for pets', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Office Supplies', 'Stationery and office equipment', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Garden & Outdoor', 'Plants and gardening tools', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Baby Products', 'Items for infants and toddlers', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Jewelry', 'Rings, necklaces, and bracelets', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Arts & Crafts', 'Supplies for creative projects', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Grocery', 'Food and household items', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9)),
(RANDOM_UUID(), 'Tools & Home Improvement', 'Hardware and tools for home projects', true, LOCALTIMESTAMP(9), LOCALTIMESTAMP(9));