### Create a new Category
POST http://localhost:8080/categories
Content-Type: application/json

{
    "name": "Electronics",
    "description": "Devices and gadgets"
}

### List all Categories
GET http://localhost:8080/categories

### List Categories with Pagination
GET http://localhost:8080/categories?page=0&perPage=5

### Get a Category by ID
GET http://localhost:8080/categories/4f7a526b-b415-4e82-a55c-995a4d979fc1

### Return 404 for non-existing Category
GET http://localhost:8080/categories/8c859fb1-e5d6-427f-a528-0afc87a990a8

### Return 404 for non-existing Category
PUT http://localhost:8080/categories/8c859fb1-e5d6-427f-a528-0afc87a990a9
Content-Type: application/json

{
    "name": "Updated Electronics",
    "description": "Updated devices and gadgets",
    "active": true
}

### Return 400 for invalid Category data
PUT http://localhost:8080/categories/4f7a526b-b415-4e82-a55c-995a4d979fc1
Content-Type: application/json

{
    "name": "Updated Electronics",
    "description": "Updated devices and gadgets"
}

### Update a Category
PUT http://localhost:8080/categories/4f7a526b-b415-4e82-a55c-995a4d979fc1
Content-Type: application/json

{
    "name": "Updated Electronics",
    "description": "Updated devices and gadgets",
    "active": true
}

### Delete a Category
DELETE http://localhost:8080/categories/8c859fb1-e5d6-427f-a528-0afc87a990a9